services:
  invidious:
    image: quay.io/invidious/invidious:2.20260207.0
    container_name: invidious
    restart: unless-stopped
    environment:
      INVIDIOUS_CONFIG_FILE: /config/iv-config
    volumes:
      - ./config:/config
    # healthcheck:
    #   test: wget -nv --tries=1 --spider http://127.0.0.1:80/api/v1/trending || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    # logging:
    #   options:
    #     max-size: "1G"
    #     max-file: "4"
    depends_on:
      - invidious-db
    network_mode: service:invidious-ts
  invidious-ts:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: invidious
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:server
      - TS_SERVE_CONFIG=/ts-serve-config.json
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - /home/nixos/env-tailscale
    volumes:
      - invidious-ts:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /home/nixos/ts-serve-config.json:/ts-serve-config.json
    cap_add:
      - net_admin
      - sys_module
    labels:
      - com.centurylinklabs.watchtower.enable=true

  companion:
    image: quay.io/invidious/invidious-companion:latest
    restart: unless-stopped
    env_file:
      - env
    # ports:
    #  - "127.0.0.1:8282:8282"
    # logging:
    #   options:
    #     max-size: "1G"
    #     max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true
    network_mode: service:companion-ts
    labels:
      - com.centurylinklabs.watchtower.enable=true
  companion-ts:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: invidious-companion
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:server
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - /home/nixos/env-tailscale
    volumes:
      - companion-ts:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    labels:
      - com.centurylinklabs.watchtower.enable=true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  invidious-db-backup:
    image: ghcr.io/sekai-soft/postgres-backup-s3:14
    restart: unless-stopped
    env_file:
      - /home/nixos/env-backup
    environment:
      S3_PREFIX: 'invidious'
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 14
      POSTGRES_HOST: invidious-db
      POSTGRES_DATABASE: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
  
volumes:
  invidious-ts:
  companioncache:
  companion-ts:
  postgresdata:
